### ISSUE TITLE
JSON output doesn't work anymore

### ISSUE THREAD

**Issue by Flopsey** [Flopsey/homebrew-open-cask#1]
```
Traceback (most recent call last):
  File "/usr/local/Homebrew/Library/Taps/flopsey/homebrew-open-cask/cmd/brewcask-open", line 19, in <module>
    data = json.loads(p.stdout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by Flopsey** [comment]
Use `--json=v2`
